// Generated by gencpp from file request/jokeResponse.msg
// DO NOT EDIT!


#ifndef REQUEST_MESSAGE_JOKERESPONSE_H
#define REQUEST_MESSAGE_JOKERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace request
{
template <class ContainerAllocator>
struct jokeResponse_
{
  typedef jokeResponse_<ContainerAllocator> Type;

  jokeResponse_()
    : joke_return()  {
    }
  jokeResponse_(const ContainerAllocator& _alloc)
    : joke_return(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joke_return_type;
  _joke_return_type joke_return;





  typedef boost::shared_ptr< ::request::jokeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::request::jokeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct jokeResponse_

typedef ::request::jokeResponse_<std::allocator<void> > jokeResponse;

typedef boost::shared_ptr< ::request::jokeResponse > jokeResponsePtr;
typedef boost::shared_ptr< ::request::jokeResponse const> jokeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::request::jokeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::request::jokeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace request

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::request::jokeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::request::jokeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::request::jokeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::request::jokeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::request::jokeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::request::jokeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::request::jokeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06b28b8d1902c0673a2a9a54929c47d7";
  }

  static const char* value(const ::request::jokeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06b28b8d1902c067ULL;
  static const uint64_t static_value2 = 0x3a2a9a54929c47d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::request::jokeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "request/jokeResponse";
  }

  static const char* value(const ::request::jokeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::request::jokeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joke_return\n"
"\n"
;
  }

  static const char* value(const ::request::jokeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::request::jokeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joke_return);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct jokeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::request::jokeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::request::jokeResponse_<ContainerAllocator>& v)
  {
    s << indent << "joke_return: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joke_return);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REQUEST_MESSAGE_JOKERESPONSE_H
